name: Send Weekly Life Email

on:
  schedule:
    - cron: '0 12 * * 1'  # Every Monday at 08:00 UTC
  workflow_dispatch:  # Optional manual trigger from GitHub UI

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install yagmail

    - name: Run script
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python my_life_in_emailed_weeks.py